#!/usr/bin/env bash
# ============================================================
# ACFS newproj - Create a new project with full ACFS tooling
# Creates a project with git, beads (bd), Claude settings, and AGENTS.md
# Supports both CLI mode and interactive TUI wizard mode
# ============================================================

set -e

# Get script directory for sourcing other modules
NEWPROJ_SCRIPT_DIR="${NEWPROJ_SCRIPT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Track what was created for summary
declare -a CREATED_ITEMS=()

# ============================================================
# Environment Detection
# ============================================================

# Check if running in a CI environment
is_ci_environment() {
    [[ -n "${CI:-}" ]] || \
    [[ -n "${GITHUB_ACTIONS:-}" ]] || \
    [[ -n "${GITLAB_CI:-}" ]] || \
    [[ -n "${JENKINS_URL:-}" ]] || \
    [[ -n "${TRAVIS:-}" ]] || \
    [[ -n "${CIRCLECI:-}" ]] || \
    [[ "${TERM:-}" == "dumb" ]]
}

# Check if stdin is a TTY (not piped)
is_stdin_tty() {
    [[ -t 0 ]]
}

# Check if stdout is a TTY
is_stdout_tty() {
    [[ -t 1 ]]
}

# Get terminal dimensions
get_terminal_size() {
    local cols lines
    cols=$(tput cols 2>/dev/null || echo 0)
    lines=$(tput lines 2>/dev/null || echo 0)
    echo "$cols $lines"
}

# Check if terminal meets minimum size requirements
check_terminal_size() {
    local min_cols="${1:-60}"
    local min_lines="${2:-15}"

    local size
    size=$(get_terminal_size)
    local cols="${size%% *}"
    local lines="${size##* }"

    if [[ "$cols" -lt "$min_cols" ]] || [[ "$lines" -lt "$min_lines" ]]; then
        echo "Terminal too small: ${cols}x${lines} (minimum: ${min_cols}x${min_lines})"
        return 1
    fi
    return 0
}

# Check if TUI module is available
check_tui_available() {
    local screens_module="$NEWPROJ_SCRIPT_DIR/newproj_screens.sh"
    if [[ ! -f "$screens_module" ]]; then
        echo "TUI module not found: $screens_module"
        return 1
    fi
    return 0
}

print_help() {
    echo "Usage: acfs newproj [options] <project-name> [directory]"
    echo "       acfs newproj --interactive"
    echo ""
    echo "Create a new project with ACFS tooling (git, bd, claude settings, AGENTS.md)"
    echo ""
    echo "Arguments:"
    echo "  project-name    Name of the project (required in CLI mode)"
    echo "  directory       Directory path (default: /data/projects/<project-name>)"
    echo ""
    echo "Interactive mode:"
    echo "  -i, --interactive   Launch TUI wizard for guided project setup"
    echo "                      (recommended for first-time users)"
    echo ""
    echo "CLI mode options:"
    echo "  --no-bd         Skip beads (bd) initialization"
    echo "  --no-claude     Skip Claude settings creation"
    echo "  --no-agents     Skip AGENTS.md template creation"
    echo "  -h, --help      Show this help message"
    echo ""
    echo "Examples:"
    echo "  acfs newproj myapp                       # CLI mode"
    echo "  acfs newproj myapp /home/user/projects   # CLI mode with custom dir"
    echo "  acfs newproj --interactive               # TUI wizard"
    echo "  acfs newproj -i                          # TUI wizard (short form)"
    echo "  acfs newproj -i myapp                    # TUI with pre-filled name"
}

# Create AGENTS.md template with ACFS tooling instructions
# Generic sections are included; project-specific sections have placeholders
create_agents_template() {
    local project_name="$1"
    cat > AGENTS.md << 'AGENTS_EOF'
# AGENTS.md — PROJECT_NAME_PLACEHOLDER

This file was generated by `acfs newproj` as a starting template.

If you used the interactive wizard, toolchain and Docker workflow sections
may be included based on detected tech stack. In CLI mode, this template is
generic - edit or add sections as needed.

To regenerate with different options, move this file aside and re-run:
  acfs newproj --interactive

---

## RULE 1 – ABSOLUTE (DO NOT EVER VIOLATE THIS)

You may NOT delete any file or directory unless I explicitly give the exact command **in this session**.

- This includes files you just created (tests, tmp files, scripts, etc.).
- You do not get to decide that something is "safe" to remove.
- If you think something should be removed, stop and ask. You must receive clear written approval **before** any deletion command is even proposed.

Treat "never delete files without permission" as a hard invariant.

---

## IRREVERSIBLE GIT & FILESYSTEM ACTIONS

Absolutely forbidden unless I give the **exact command and explicit approval** in the same message:

- `git reset --hard`
- `git clean -fd`
- `rm -rf`
- Any command that can delete or overwrite code/data

Rules:

1. If you are not 100% sure what a command will delete, do not propose or run it. Ask first.
2. Prefer safe tools: `git status`, `git diff`, `git stash`, copying to backups, etc.
3. After approval, restate the command verbatim, list what it will affect, and wait for confirmation.
4. When a destructive command is run, record in your response:
   - The exact user text authorizing it
   - The command run
   - When you ran it

If that audit trail is missing, then you must act as if the operation never happened.

---

## Node / JS Toolchain

- Use **bun** for everything JS/TS.
- ❌ Never use `npm`, `yarn`, or `pnpm`.
- Lockfiles: only `bun.lock`. Do not introduce any other lockfile.
- Target **latest Node.js**. No need to support old Node versions.
- **Note:** `bun install -g <pkg>` is valid syntax (alias for `bun add -g`). Do not "fix" it.

---

## Project Architecture

<!-- CUSTOMIZE: Describe your project's architecture here -->

### Components

<!-- CUSTOMIZE: List your project's main components/domains -->

Example structure:
- **A) Backend API** — Framework, database, main responsibilities
- **B) Frontend** — Framework, UI library, key patterns
- **C) Shared** — Common utilities, types, constants

---

## Repo Layout

<!-- CUSTOMIZE: Document your actual directory structure -->

```
PROJECT_NAME_PLACEHOLDER/
├── README.md
├── AGENTS.md
├── .beads/                        # Issue tracking (bd)
├── .claude/                       # Claude Code settings
│
└── src/                           # Your source code
```

---

## Generated Files — NEVER Edit Manually

<!-- CUSTOMIZE: If you have generated files, document them here -->

**Current state:** There are no generated files in this repo.

If/when you add generated artifacts:
- **Rule:** Never hand-edit generated outputs.
- **Convention:** Put generated outputs in a clearly labeled directory and document the generator command.

---

## Code Editing Discipline

- Do **not** run scripts that bulk-modify code (codemods, invented one-off scripts, giant `sed`/regex refactors).
- Large mechanical changes: break into smaller, explicit edits and review diffs.
- Subtle/complex changes: edit by hand, file-by-file, with careful reasoning.

---

## Backwards Compatibility & File Sprawl

We optimize for a clean architecture now, not backwards compatibility.

- No "compat shims" or "v2" file clones.
- When changing behavior, migrate callers and remove old code.
- New files are only for genuinely new domains that don't fit existing modules.
- The bar for adding files is very high.

---

## Console Output

- Prefer **structured, minimal logs** (avoid spammy debug output).
- Treat user-facing UX as UI-first; logs are for operators/debugging.

---

## MCP Agent Mail — Multi-Agent Coordination

Agent Mail is available as an MCP server for coordinating work across agents.

What Agent Mail gives:
- Identities, inbox/outbox, searchable threads.
- Advisory file reservations (leases) to avoid agents clobbering each other.
- Persistent artifacts in git (human-auditable).

Core patterns:

1. **Same repo**
   - Register identity:
     - `ensure_project` then `register_agent` with the repo's absolute path as `project_key`.
   - Reserve files before editing:
     - `file_reservation_paths(project_key, agent_name, ["src/**"], ttl_seconds=3600, exclusive=true)`.
   - Communicate:
     - `send_message(..., thread_id="FEAT-123")`.
     - `fetch_inbox`, then `acknowledge_message`.
   - Fast reads:
     - `resource://inbox/{Agent}?project=<abs-path>&limit=20`.
     - `resource://thread/{id}?project=<abs-path>&include_bodies=true`.

2. **Macros vs granular:**
   - Prefer macros when speed is more important than fine-grained control:
     - `macro_start_session`, `macro_prepare_thread`, `macro_file_reservation_cycle`, `macro_contact_handshake`.
   - Use granular tools when you need explicit behavior.

Common pitfalls:
- "from_agent not registered" → call `register_agent` with correct `project_key`.
- `FILE_RESERVATION_CONFLICT` → adjust patterns, wait for expiry, or use non-exclusive reservation.

---

## Landing the Plane (Session Completion)

**When ending a work session**, you MUST complete ALL steps below. Work is NOT complete until `git push` succeeds.

**MANDATORY WORKFLOW:**

1. **File issues for remaining work** - Create issues for anything that needs follow-up
2. **Run quality gates** (if code changed) - Tests, linters, builds
3. **Update issue status** - Close finished work, update in-progress items
4. **PUSH TO REMOTE** - This is MANDATORY:
   ```bash
   git pull --rebase
   br sync --flush-only
   git add .beads/
   git commit -m "Update beads"
   git push
   git status  # MUST show "up to date with origin"
   ```
5. **Clean up** - Clear stashes, prune remote branches
6. **Verify** - All changes committed AND pushed
7. **Hand off** - Provide context for next session

**CRITICAL RULES:**
- Work is NOT complete until `git push` succeeds
- NEVER stop before pushing - that leaves work stranded locally
- NEVER say "ready to push when you are" - YOU must push
- If push fails, resolve and retry until it succeeds

---

## Issue Tracking with br (Beads)

All issue tracking goes through **Beads**. No other TODO systems.

**Note:** `br` is a convenience alias (installed by `acfs/zsh/acfs.zshrc`) for the real Beads CLI: `bd`.
If `br` is unavailable (CI / non-interactive shells), use `bd` directly.

Key invariants:

- `.beads/` is authoritative state and **must always be committed** with code changes.
- Do not edit `.beads/*.jsonl` directly; only via `br` / `bd`.

### Basics

Check ready work:

```bash
br ready --json
```

Create issues:

```bash
br create "Issue title" -t bug|feature|task -p 0-4 --json
br create "Issue title" -p 1 --deps discovered-from:br-123 --json
```

Update:

```bash
br update br-42 --status in_progress --json
br update br-42 --priority 1 --json
```

Complete:

```bash
br close br-42 --reason "Completed" --json
```

Types: `bug`, `feature`, `task`, `epic`, `chore`

Priorities: `0` critical, `1` high, `2` medium (default), `3` low, `4` backlog

Agent workflow:

1. `br ready` to find unblocked work.
2. Claim: `br update <id> --status in_progress`.
3. Implement + test.
4. If you discover new work, create a new bead with `discovered-from:<parent-id>`.
5. Close when done.
6. Commit `.beads/` in the same commit as code changes.

Never:
- Use markdown TODO lists.
- Use other trackers.
- Duplicate tracking.

---

## Using bv as an AI sidecar

bv is a graph-aware triage engine for Beads projects. Use robot flags for deterministic outputs.

**⚠️ CRITICAL: Use ONLY `--robot-*` flags. Bare `bv` launches an interactive TUI that blocks your session.**

```bash
bv --robot-triage        # THE MEGA-COMMAND: start here
bv --robot-next          # Just the single top pick + claim command
bv --robot-plan          # Parallel execution tracks
bv --robot-insights      # Full graph metrics
```

Use bv instead of parsing beads.jsonl—it computes PageRank, critical paths, cycles, and parallel tracks deterministically.

---

## cass — Cross-Agent Search

`cass` indexes prior agent conversations so we can reuse solved problems.

**Rules:** Never run bare `cass` (TUI). Always use `--robot` or `--json`.

```bash
cass health
cass search "authentication error" --robot --limit 5
cass view /path/to/session.jsonl -n 42 --json
```

Treat cass as a way to avoid re-solving problems other agents already handled.

---

## Memory System: cass-memory

Before starting complex tasks, retrieve relevant context:

```bash
cm context "<task description>" --json
```

This returns:
- **relevantBullets**: Rules that may help with your task
- **antiPatterns**: Pitfalls to avoid
- **historySnippets**: Past sessions that solved similar problems

Protocol:
1. **START**: Run `cm context "<task>" --json` before non-trivial work
2. **WORK**: Reference rule IDs when following them
3. **END**: Just finish your work. Learning happens automatically.

---

## UBS Quick Reference

**Golden Rule:** `ubs <changed-files>` before every commit. Exit 0 = safe. Exit >0 = fix & re-run.

```bash
ubs file.ts file2.py                    # Specific files (< 1s) — USE THIS
ubs $(git diff --name-only --cached)    # Staged files — before commit
ubs .                                   # Whole project
```

**Speed Critical:** Scope to changed files. `ubs src/file.ts` (< 1s) vs `ubs .` (30s).

**Bug Severity:**
- **Critical** (always fix): Null safety, XSS/injection, async/await, memory leaks
- **Important** (production): Type narrowing, division-by-zero, resource leaks
- **Contextual** (judgment): TODO/FIXME, console logs
AGENTS_EOF

    # Replace placeholder with actual project name
    # Use portable sed syntax that works on both GNU (Linux) and BSD (macOS)
    sed -i.bak "s/PROJECT_NAME_PLACEHOLDER/$project_name/g" AGENTS.md && rm -f AGENTS.md.bak
}

# ============================================================
# Interactive Mode
# ============================================================

# Run the interactive TUI wizard
# Usage: run_interactive_mode [prefill_name] [prefill_dir]
run_interactive_mode() {
    local prefill_name="${1:-}"
    local prefill_dir="${2:-}"

    # Pre-flight checks for interactive mode
    echo -e "${CYAN}Checking interactive mode requirements...${NC}"

    # Check 1: CI environment
    if is_ci_environment; then
        echo -e "${RED}Error: Interactive mode cannot run in CI environment${NC}" >&2
        echo -e "${YELLOW}Detected CI environment variables or TERM=dumb${NC}" >&2
        echo -e "${YELLOW}Use CLI mode instead: acfs newproj <project-name>${NC}" >&2
        return 1
    fi

    # Check 2: TTY requirement
    if ! is_stdin_tty; then
        echo -e "${RED}Error: Interactive mode requires a terminal (stdin is not a TTY)${NC}" >&2
        echo -e "${YELLOW}Cannot run in piped input mode${NC}" >&2
        echo -e "${YELLOW}Use CLI mode instead: acfs newproj <project-name>${NC}" >&2
        return 1
    fi

    if ! is_stdout_tty; then
        echo -e "${RED}Error: Interactive mode requires a terminal (stdout is not a TTY)${NC}" >&2
        echo -e "${YELLOW}Cannot run with redirected output${NC}" >&2
        echo -e "${YELLOW}Use CLI mode instead: acfs newproj <project-name>${NC}" >&2
        return 1
    fi

    # Check 3: Terminal size
    local size_error
    size_error=$(check_terminal_size 60 15) || {
        echo -e "${RED}Error: $size_error${NC}" >&2
        echo -e "${YELLOW}Please resize your terminal and try again${NC}" >&2
        return 1
    }

    # Check 4: TUI module availability
    local tui_error
    tui_error=$(check_tui_available) || {
        echo -e "${RED}Error: $tui_error${NC}" >&2
        echo -e "${YELLOW}The TUI wizard module may not be installed correctly${NC}" >&2
        echo -e "${YELLOW}Try reinstalling ACFS or use CLI mode${NC}" >&2
        return 1
    }

    echo -e "${GREEN}All checks passed, launching wizard...${NC}"
    echo ""

    # Source the screens module
    source "$NEWPROJ_SCRIPT_DIR/newproj_screens.sh"

    # Pre-fill state if arguments provided
    if [[ -n "$prefill_name" ]]; then
        echo -e "${CYAN}Pre-filling project name: $prefill_name${NC}"
        state_set "project_name" "$prefill_name"
    fi

    if [[ -n "$prefill_dir" ]]; then
        echo -e "${CYAN}Pre-filling project directory: $prefill_dir${NC}"
        state_set "project_dir" "$prefill_dir"
    fi

    # Run the wizard
    if run_wizard; then
        return 0
    else
        # Wizard was cancelled or failed
        echo ""
        echo -e "${YELLOW}Wizard cancelled or failed${NC}"
        return 1
    fi
}

main() {
    local project_name=""
    local project_dir=""
    local skip_bd=false
    local skip_claude=false
    local skip_agents=false
    local interactive_mode=false

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h|--help)
                print_help
                exit 0
                ;;
            -i|--interactive)
                interactive_mode=true
                shift
                ;;
            --no-bd)
                skip_bd=true
                shift
                ;;
            --no-claude)
                skip_claude=true
                shift
                ;;
            --no-agents)
                skip_agents=true
                shift
                ;;
            -*)
                echo -e "${RED}Unknown option: $1${NC}" >&2
                print_help
                exit 1
                ;;
            *)
                if [[ -z "$project_name" ]]; then
                    project_name="$1"
                elif [[ -z "$project_dir" ]]; then
                    project_dir="$1"
                else
                    echo -e "${RED}Too many arguments${NC}" >&2
                    print_help
                    exit 1
                fi
                shift
                ;;
        esac
    done

    # Handle interactive mode
    if [[ "$interactive_mode" == "true" ]]; then
        run_interactive_mode "$project_name" "$project_dir"
        return $?
    fi

    # Validate project name
    if [[ -z "$project_name" ]]; then
        echo -e "${RED}Error: Project name is required${NC}" >&2
        print_help
        exit 1
    fi

    # Validate project name format (alphanumeric, hyphens, underscores)
    # Allow dots for domain-style names (e.g. com.example.app), but ensure it starts with alphanumeric
    if [[ ! "$project_name" =~ ^[a-zA-Z0-9][a-zA-Z0-9._-]*$ ]]; then
        echo -e "${RED}Error: Project name must start with a letter/number and contain only letters, numbers, hyphens, underscores, and dots${NC}" >&2
        exit 1
    fi

    # SAFEGUARD: Reject test-like project names that may leak from test frameworks
    # This prevents BATS tests from accidentally creating projects in /data/projects
    if [[ "$project_name" =~ ^test_ ]]; then
        echo -e "${RED}Error: Project names starting with 'test_' are not allowed${NC}" >&2
        echo -e "${YELLOW}This safeguard prevents test framework pollution of /data/projects${NC}" >&2
        echo -e "${YELLOW}If this is intentional, use a different naming convention${NC}" >&2
        exit 1
    fi

    # SAFEGUARD: Reject names with hex-encoded characters (e.g., -2d, -5f, -3d)
    # These patterns indicate test framework name encoding that leaked into production
    if [[ "$project_name" =~ -[0-9a-f]{2} ]]; then
        echo -e "${RED}Error: Project name contains hex-encoded characters (e.g., -2d, -5f)${NC}" >&2
        echo -e "${YELLOW}This pattern suggests a test framework encoding leak${NC}" >&2
        exit 1
    fi

    # Set default directory
    # SAFEGUARD: When running in test environment, ALWAYS use /tmp to prevent pollution
    if [[ -n "${BATS_TEST_NAME:-}" || -n "${ACFS_TEST_MODE:-}" ]]; then
        if [[ -z "$project_dir" ]]; then
            project_dir="/tmp/acfs-test-$$/$project_name"
            echo -e "${YELLOW}Test mode detected: redirecting to $project_dir${NC}" >&2
        fi
    elif [[ -z "$project_dir" ]]; then
        project_dir="/data/projects/$project_name"
    fi

    # Check if directory already exists
    if [[ -d "$project_dir" ]]; then
        echo -e "${YELLOW}Warning: Directory $project_dir already exists${NC}"
        if [[ -d "$project_dir/.git" ]]; then
            echo -e "${CYAN}Git repository already initialized${NC}"
        fi
    fi

    echo -e "${CYAN}Creating project: $project_name${NC}"
    echo -e "${CYAN}Directory: $project_dir${NC}"
    echo ""

    # Create directory
    mkdir -p "$project_dir"
    cd "$project_dir" || {
        echo -e "${RED}Error: Failed to enter project directory: $project_dir${NC}" >&2
        exit 1
    }

    # Initialize git if not already
    if [[ ! -d .git ]]; then
        echo -e "${GREEN}Initializing git repository...${NC}"
        git init
        CREATED_ITEMS+=("Git repository")

        # Create README
        echo "# $project_name" > README.md
        CREATED_ITEMS+=("README.md")

        # Create universal .gitignore (patterns that apply to ALL project types)
        cat > .gitignore << 'EOF'
# OS/Editor artifacts
.DS_Store
Thumbs.db
*~
*.swp
*.swo
.idea/
.vscode/
*.sublime-*

# Environment/secrets (never commit these)
.env
.env.*
!.env.example

# Logs
*.log
logs/
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Build artifacts (add project-specific patterns below)
dist/
build/
*.pyc
__pycache__/
node_modules/
.venv/
venv/
EOF
        CREATED_ITEMS+=(".gitignore")

        # Create universal .ubsignore (patterns for UBS bug scanner)
        cat > .ubsignore << 'EOF'
# UBS ignore globs (keep bug scanner focused on source code)
# Patterns are evaluated relative to the project root.

# Dependencies / vendored (never scan third-party code)
node_modules/
**/node_modules/

# Python virtual environments
.venv/
venv/
.tox/

# Build outputs (scan source, not artifacts)
dist/
build/
.next/
out/
target/
*.egg-info/

# Test artifacts
coverage/
.coverage
htmlcov/
.pytest_cache/
playwright-report/
test-results/

# IDE/Editor
.idea/
.vscode/

# Package manager caches
.npm/
.pnpm-store/
.yarn/
EOF
        CREATED_ITEMS+=(".ubsignore")

        git add README.md .gitignore .ubsignore

        # Check if git user is configured before committing
        if git config user.name &>/dev/null && git config user.email &>/dev/null; then
            git commit -m "Initial commit"
        else
            echo -e "${YELLOW}Warning: Git user not configured, skipping initial commit${NC}"
            echo -e "${YELLOW}Run: git config --global user.name \"Your Name\"${NC}"
            echo -e "${YELLOW}     git config --global user.email \"you@example.com\"${NC}"
        fi
    else
        echo -e "${CYAN}Git already initialized, skipping${NC}"
    fi

    # Initialize beads (bd) if available and not skipped
    if [[ "$skip_bd" == "false" ]]; then
        if command -v bd &>/dev/null; then
            if [[ ! -d .beads ]]; then
                echo -e "${GREEN}Initializing beads (bd)...${NC}"
                bd init
                CREATED_ITEMS+=("Beads tracking (.beads/)")
            else
                echo -e "${CYAN}Beads already initialized, skipping${NC}"
            fi
        else
            echo -e "${YELLOW}Warning: bd not found, skipping beads initialization${NC}"
            echo -e "${YELLOW}Install with: curl -fsSL https://agent-flywheel.com/install | bash -s -- --yes --only stack.beads_viewer${NC}"
        fi
    fi

    # Create Claude settings if not skipped
    if [[ "$skip_claude" == "false" ]]; then
        mkdir -p .claude/commands

        if [[ ! -f .claude/settings.toml ]]; then
            echo -e "${GREEN}Creating Claude settings...${NC}"
            cat > .claude/settings.toml << 'EOF'
# Claude Code project settings
# See: https://docs.anthropic.com/en/docs/claude-code/settings

[project]
# Project-specific settings go here

[permissions]
# allow = ["Bash(npm:*)", "Bash(bun:*)"]
EOF
            CREATED_ITEMS+=("Claude settings (.claude/)")
        else
            echo -e "${CYAN}Claude settings already exist, skipping${NC}"
        fi
    fi

    # Create AGENTS.md template if not skipped
    if [[ "$skip_agents" == "false" ]]; then
        if [[ ! -f AGENTS.md ]]; then
            echo -e "${GREEN}Creating AGENTS.md template...${NC}"
            create_agents_template "$project_name"
            CREATED_ITEMS+=("AGENTS.md (template)")
        else
            echo -e "${CYAN}AGENTS.md already exists, skipping${NC}"
        fi
    fi

    # Print summary of what was created
    echo ""
    if [[ ${#CREATED_ITEMS[@]} -gt 0 ]]; then
        echo -e "${GREEN}Created:${NC}"
        for item in "${CREATED_ITEMS[@]}"; do
            echo -e "  ${GREEN}✓${NC} $item"
        done
    fi

    echo ""
    echo -e "${GREEN}Project $project_name ready at $project_dir${NC}"
    echo ""
    echo "Next steps:"
    echo "  cd $project_dir"
    if [[ "$skip_agents" == "false" ]] && [[ -f AGENTS.md ]]; then
        echo "  # Edit AGENTS.md to customize for your project"
    fi
    if [[ "$skip_bd" == "false" ]] && command -v bd &>/dev/null; then
        echo "  bd ready                    # Check for work"
        echo "  bd create --title=\"...\"    # Create tasks"
    fi
    echo "  cc                          # Start Claude Code"
}

# Only run main if script is executed directly, not sourced
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
